### ISSUE TITLE
Use random.choice

### ISSUE THREAD

**Issue by Steve0Greatness** [leahcimto/randomJokeAPI#1]
https://github.com/leahcimto/randomJokeAPI/blob/67f681dc985d193c5fed82342d7119ed9f65af0a/main.py#L15
Here, random.choice does the same job:
```python
return  { "joke": random.choice(jokes) }
```
There is no competition here.  
`random.choice(jokes)` > `jokes[random.randrange(0, len(jokes))]`

**Comment by leahcimto** [comment]
Thanks for the issue, resolved by 23d7e39
